package store

import (
	"context"
	"database/sql"
	"errors"
)

// Owner is a dashboard account that owns channels and their configs.
type Owner struct {
	ID       int64
	Email    string
	PassHash string
}

// CreateOwner inserts a new owner and returns its id.
func (s *Store) CreateOwner(ctx context.Context, email, passHash string) (int64, error) {
	res, err := s.db.ExecContext(ctx,
		`INSERT INTO owners (email, pass_hash) VALUES (?, ?)`, email, passHash)
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

// OwnerByEmail looks up an owner by login email. Returns sql.ErrNoRows if absent.
func (s *Store) OwnerByEmail(ctx context.Context, email string) (*Owner, error) {
	o := &Owner{}
	err := s.db.QueryRowContext(ctx,
		`SELECT id, email, pass_hash FROM owners WHERE email = ?`, email).
		Scan(&o.ID, &o.Email, &o.PassHash)
	if err != nil {
		return nil, err
	}
	return o, nil
}

// OwnerByID looks up an owner by id.
func (s *Store) OwnerByID(ctx context.Context, id int64) (*Owner, error) {
	o := &Owner{}
	err := s.db.QueryRowContext(ctx,
		`SELECT id, email, pass_hash FROM owners WHERE id = ?`, id).
		Scan(&o.ID, &o.Email, &o.PassHash)
	if err != nil {
		return nil, err
	}
	return o, nil
}

// CreateChannel inserts a channel owned by ownerID and returns its id.
// ref is generated by the caller and must be unique.
func (s *Store) CreateChannel(ctx context.Context, ownerID int64, ref, title string, adText, telegramURL *string) (int64, error) {
	res, err := s.db.ExecContext(ctx,
		`INSERT INTO channels (ref, owner_id, title, telegram_url, ad_text, status)
		 VALUES (?, ?, ?, ?, ?, 'active')`,
		ref, ownerID, title, telegramURL, adText)
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

// ChannelsByOwner lists all channels belonging to an owner.
func (s *Store) ChannelsByOwner(ctx context.Context, ownerID int64) ([]Channel, error) {
	rows, err := s.db.QueryContext(ctx,
		`SELECT id, ref, owner_id, title, telegram_url, ad_text, status, config_count
		 FROM channels WHERE owner_id = ? ORDER BY created_at`, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Channel
	for rows.Next() {
		var c Channel
		if err := rows.Scan(&c.ID, &c.Ref, &c.OwnerID, &c.Title, &c.TelegramURL, &c.AdText, &c.Status, &c.ConfigCount); err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// ChannelByID looks up a channel by id.
func (s *Store) ChannelByID(ctx context.Context, id int64) (*Channel, error) {
	c := &Channel{}
	err := s.db.QueryRowContext(ctx,
		`SELECT id, ref, owner_id, title, telegram_url, ad_text, status, config_count
		 FROM channels WHERE id = ?`, id).
		Scan(&c.ID, &c.Ref, &c.OwnerID, &c.Title, &c.TelegramURL, &c.AdText, &c.Status, &c.ConfigCount)
	if err != nil {
		return nil, err
	}
	return c, nil
}

// ChannelOwnedBy returns a channel if it exists and belongs to ownerID.
func (s *Store) ChannelOwnedBy(ctx context.Context, ownerID int64, ref string) (*Channel, error) {
	c := &Channel{}
	err := s.db.QueryRowContext(ctx,
		`SELECT id, ref, owner_id, title, telegram_url, ad_text, status, config_count
		 FROM channels WHERE ref = ? AND owner_id = ?`, ref, ownerID).
		Scan(&c.ID, &c.Ref, &c.OwnerID, &c.Title, &c.TelegramURL, &c.AdText, &c.Status, &c.ConfigCount)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, err
	}
	return c, nil
}

// UpdateChannelAd updates the telegram ad text + url for a channel.
func (s *Store) UpdateChannelAd(ctx context.Context, channelID int64, adText, telegramURL *string) error {
	_, err := s.db.ExecContext(ctx,
		`UPDATE channels SET ad_text = ?, telegram_url = ? WHERE id = ?`, adText, telegramURL, channelID)
	return err
}

// RevokeChannel marks all blobs of a channel revoked and the channel itself revoked.
func (s *Store) RevokeChannel(ctx context.Context, channelID int64) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.ExecContext(ctx, `UPDATE blobs SET status='revoked' WHERE channel_id = ?`, channelID); err != nil {
		return err
	}
	if _, err := tx.ExecContext(ctx, `UPDATE channels SET status='revoked' WHERE id = ?`, channelID); err != nil {
		return err
	}
	return tx.Commit()
}
